"""
Billing App Models
Purpose: Define the Order model for RabbitMQ message consumer
Reference: CRUD_Master_README.md Section 7.3
"""

from datetime import datetime
from app.db import db


class Order(db.Model):
    """
    Order Model - represents a movie order from a customer
    
    This model stores billing information for orders received from the RabbitMQ queue.
    Orders are created asynchronously by the RabbitMQ consumer when messages arrive
    in the billing_queue.
    
    Table name: orders
    Database: PostgreSQL on billing-vm
    """
    
    __tablename__ = 'orders'
    
    # Primary Key - Auto-incrementing unique identifier
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True,
        doc="Unique order ID (auto-generated by PostgreSQL)"
    )
    
    # Customer identifier (required)
    user_id = db.Column(
        db.String(100),
        nullable=False,
        doc="Customer/User ID who placed this order"
    )
    
    # Number of items in the order (required)
    number_of_items = db.Column(
        db.String(10),
        nullable=False,
        doc="Number of movie items/copies in this order"
    )
    
    # Total cost of the order (required)
    total_amount = db.Column(
        db.String(50),
        nullable=False,
        doc="Total cost of the order in currency units"
    )
    
    # Timestamp when the order was created (auto-set)
    created_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        doc="Timestamp when order was received and processed"
    )
    
    def to_dict(self):
        """
        Convert Order object to dictionary for JSON serialization
        
        Returns:
            dict: Order data in JSON-serializable format
        """
        return {
            'id': self.id,
            'user_id': self.user_id,
            'number_of_items': self.number_of_items,
            'total_amount': self.total_amount,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    def __repr__(self):
        """String representation of Order object"""
        return f"<Order id={self.id}, user_id={self.user_id}, amount={self.total_amount}>"
