# Use the penultimate Debian version
FROM debian:bullseye-slim

# Install RabbitMQ and necessary utilities
# We use -slim to keep the image size down
RUN apt-get update && apt-get install -y --no-install-recommends \
    rabbitmq-server \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Ensure RabbitMQ can run in the foreground
# Debian's rabbitmq-server package starts a background daemon by default
# We need it to stay alive for the container
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# RabbitMQ Ports
EXPOSE 5672 15672

ENTRYPOINT ["entrypoint.sh"]
